# Generated by Django 4.2 on 2023-05-04 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 19, 25, 59, 506664, tzinfo=datetime.timezone.utc)),
        ),
    ]
