# Generated by Django 4.2 on 2023-05-04 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 20, 24, 50, 415953, tzinfo=datetime.timezone.utc)),
        ),
    ]
