# Generated by Django 4.2 on 2023-05-05 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 5, 12, 18, 17, 849336, tzinfo=datetime.timezone.utc)),
        ),
    ]
