# Generated by Django 4.2 on 2023-05-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_contactus_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='text',
        ),
    ]
