# Generated by Django 4.2 on 2023-05-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_contactus_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
    ]
